name: Deploy NuGet(OTAPI3)

on:
  push:
    branches: [ nuget-release ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: release

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build TSAPI.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release --filter "FullyQualifiedName!~TerrariaServerAPI.Tests.Benchmarks"

    # Publish
    - name: Push TSAPI
      run: dotnet nuget push TerrariaServerAPI/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
